### ISSUE TITLE
Question on webpage contents

### ISSUE THREAD

**Issue by Seo-Young** [vmarkovtsev/veles-slanding#4]
In the webpage, there's a sentence 'Tens of plotting units provide comprehensive insight into the training process.'
plotting unit is right? what is the plotting units?

**Comment by vmarkovtsev** [comment]
It is something to deal with our project's terminology. Briefly, "plotting unit" is a class which draws graphs about what's happening inside. E.g., if we are training AI to classify people to "male" and "female", there is a unit which plots how the error decreases over time:

![graph](http://d1u2s20mo6at4b.cloudfront.net/wp-content/uploads/gradient_descent_error_by_iteration.png)

**Comment by Seo-Young** [comment]
I see. Thanks for the explanation
